### ISSUE TITLE
Moodle announcements forwarding system

### ISSUE THREAD

**Issue by SlamaFR** [SlamaFR/UGE-Bot#30]
Okay, so this will be a huge mess.

We need a system that can log into a mail inbox and listen for new mails. For each mail received, the system has to differentiate automatic Moodle mails and normal mails. After that, the bot will format the message and send it in the correct channel (given in config).

**Comment by SlamaFR** [comment]
https://github.com/jakobkmar/SimpleKotlinMail

**Comment by notKamui** [comment]
https://github.com/notKamui/Kourrier

flexing mmmy'know
