### ISSUE TITLE
Poll message edition fails after long timeout.

### ISSUE THREAD

**Issue by SlamaFR** [SlamaFR/UGE-Bot#65]
If you call a poll with a pretty long timeout (at least 2 hours from my experience), the message is not successfully edited to show the poll results. 

This should be easily fixed by retrieving the message by its ID before editing it, to void cache erasure issues.

**Comment by notKamui** [comment]
discord dumdumb

**Comment by notKamui** [comment]
note that the same issue will happen with every command that has a timeout, like `call`
